### ISSUE TITLE
Theories parsing bug

### ISSUE THREAD

**Issue by dohan** [hhu-stups/camille#14]
It seems that camille is not able to parse operators (of theory modules) with more than 1 argument.
For example, camille can not parse the seqAppend(s, e) operator:
![bildschirmfoto 2014-08-19 um 11 07 21](https://cloud.githubusercontent.com/assets/1628840/3963791/d27868be-2780-11e4-9739-75051d5bbf62.png)

**Comment by wysiib** [comment]
Theories have been released, so maybe we are able to fix the bug. Can you send my an example project where the problem occurs?

**Comment by leuschel** [comment]
> On 27 Jan 2015, at 11:10, Sebastian Krings <notifications@github.com> wrote:
> 
> Theories have been released, so maybe we are able to fix the bug. Can you send my an example project where the problem occurs?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/hhu-stups/camille/issues/14#issuecomment-71620871>.
> 


Example attached:

context TestBool
constants a b c
axioms
 @axm a∈BOOL ∧ b∈BOOL ∧c∈BOOL
 @axm1 a=NOT(b)
 @axm2 c = AND(a,b)
end

**Comment by wysiib** [comment]
Might be fixed in latest nightly, please verify.
