### ISSUE TITLE
Wrong overriding simbol

### ISSUE THREAD

**Issue by GeGerardo** [hhu-stups/camille#23]
The overriding simbol "<+"  In mac version becomes , in Linux version becomes ∃
<img width="171" alt="captura de tela 2016-03-18 as 14 47 54" src="https://cloud.githubusercontent.com/assets/17926153/13887045/8afb1086-ed18-11e5-86b0-82e8e851159a.png">

**Comment by wysiib** [comment]
Duplicate of #18
